#!/bin/sh

# Avis startup script for Mac OS X (10.4 and later)

# Standard system config
. /etc/rc.common

# Set default parameters
AVISD=/usr/local/sbin/avisd
AVISD_CONFDIR=/usr/local/etc/avis
AVISD_CONF=$AVISD_CONFDIR/avisd.config
AVISD_OPTS=""
AVISD_PIDFILE=/var/run/avisd.pid
AVISD_LOGILE=/dev/console

StartService ()
{
    ##
    # Start Avis Router
    ##
    PIDFILE=$AVISD_PIDFILE
    if ! pid=$(GetPID avisd); then
      ConsoleMessage "Starting Avis Event Router"
      $AVISD -daemon -pidfile $AVISD_PIDFILE -logfile $AVISD_LOGILE \
        -c $AVISD_CONF $AVISD_OPTS
    fi
}

StopService ()
{
    ConsoleMessage "Stopping Avis Event Router"
    kill -INT $(cat $AVISD_PIDFILE)
}

RestartService () 
{
    StopService
    sleep 5
    StartService
}

RunService "$1"
