package org.avis.federation;

public enum AstType
{
  EMPTY, NAME, TYPE_INT32, TYPE_INT64, TYPE_REAL64, TYPE_STRING, REGEXP, 
  EQUALS, NOT_EQUALS, LESS_THAN, LESS_THAN_EQUALS, GREATER_THAN, 
  GREATER_THAN_EQUALS, OR, XOR, AND, NOT, UNARY_PLUS, UNARY_MINUS, 
  MULTIPLY, DIVIDE, MODULO, ADD, SUBTRACT, SHIFT_LEFT, SHIFT_RIGHT, 
  LOGICAL_SHIFT_RIGHT, BIT_AND, BIT_XOR, BIT_OR, BIT_NEGATE, INT32, 
  INT64, REAL64, STRING, OPAQUE, NAN, BEGINS_WITH, CONTAINS, ENDS_WITH, 
  WILDCARD, REGEX, TO_LOWER, TO_UPPER, PRIMARY, SECONDARY, TERTIARY, 
  DECOMPOSE, DECOMPOSE_COMPAT, REQUIRE, F_EQUALS, SIZE;
}
