/* Generated By:JavaCC: Do not edit this line. SubscriptionParserConstants.java */
package org.avis.subscription.parser;

public interface SubscriptionParserConstants {

  int EOF = 0;
  int IDENTIFIER = 5;
  int LETTER = 6;
  int ID_CHAR = 7;
  int BACKSLASH = 8;
  int INTEGER_LITERAL = 9;
  int DECIMAL_LITERAL = 10;
  int HEX_LITERAL = 11;
  int HEX_DIGIT = 12;
  int OCTAL_LITERAL = 13;
  int REAL_LITERAL = 14;
  int EXPONENT = 15;
  int STRING_LITERAL = 16;
  int DQUOTE_STRING_LITERAL = 17;
  int SQUOTE_STRING_LITERAL = 18;
  int BACKSLASH_EXPR = 19;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<ID_CHAR>",
    "<BACKSLASH>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<HEX_DIGIT>",
    "<OCTAL_LITERAL>",
    "<REAL_LITERAL>",
    "<EXPONENT>",
    "<STRING_LITERAL>",
    "<DQUOTE_STRING_LITERAL>",
    "<SQUOTE_STRING_LITERAL>",
    "<BACKSLASH_EXPR>",
    "\"||\"",
    "\"^^\"",
    "\"&&\"",
    "\"!\"",
    "\">\"",
    "\">=\"",
    "\"<\"",
    "\"<=\"",
    "\"==\"",
    "\"!=\"",
    "\"-\"",
    "\"+\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"<<\"",
    "\">>\"",
    "\">>>\"",
    "\"|\"",
    "\"^\"",
    "\"&\"",
    "\"~\"",
    "\"(\"",
    "\")\"",
    "\",\"",
  };

}
